### ISSUE TITLE
关于重建开源站点

### ISSUE THREAD

**Issue by huangjj27** [sysu/sysu.github.io#1]
旧有站点年代久远，一些项目已经不再维护，外链甚至404，因此希望能重建一个面向科学与技术的新技术站

**Comment by ltaoist** [comment]
支持！

=：：= 俺校好像也没啥正经的开源产出。。（~~不过开源好像本来就不是什么正经的事~~）

从什么地方做起呢？课程资料？

**Comment by huangjj27** [comment]
> 从什么地方做起呢？课程资料？

最好是 技术性的资料吧，毕竟我们这个是开源技术站点。也可以把一些比较出名的师兄师姐的博客发出去

**Comment by ltaoist** [comment]
> > 从什么地方做起呢？课程资料？
> 
> 最好是 技术性的资料吧，毕竟我们这个是开源技术站点。也可以把一些比较出名的师兄师姐的博客发出去

说的再深一点？

**Comment by huangjj27** [comment]
> 说的再深一点？
例如 @huangjj27 （逃

**Comment by ltaoist** [comment]
> > 说的再深一点？
> > 例如 @huangjj27 （逃

搞个二级标题（导航），“读博客、挖项目、找校友、看社区、学知识”？

读博客 -- 链接到内容比较翔实的博客？
挖项目 -- 链接到github或者项目主页？
找校友 -- 链接到校友开的公司/招聘网站？
看社区 -- 链接到合适的技术社区？
学知识 -- 其他导航的推荐的学习材料？

下面可以再加三级标题（然后再链接过去）？

**Comment by ltaoist** [comment]
@GenBill 师弟快来，毕业的师兄们没工夫管了……

**Comment by huangjj27** [comment]
> @GenBill 师弟快来，毕业的师兄们没工夫管了……

师兄求你别乱搞了！ 邮箱爆了！

**Comment by huangjj27** [comment]
看来没有人管这事了~先关掉吧~
